# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Copy source
COPY package.json tsconfig.json .
COPY src ./src

# Install dependencies without authentication issues
RUN npm install --ignore-scripts

# Build TypeScript
RUN npm run build

# Default command
CMD ["node", "build/index.js"]
